import { FormEvent, useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import ApprovalCard from "./ApprovalCard";
import MessageList from "./MessageList";
import { useConversationStore, type Conversation } from "../stores/conversationStore";
import { hydrateConversationMessages } from "../lib/conversationHydrate";
import { useLocaleStore } from "../stores/localeStore";

export default function ChatView() {
  const [input, setInput] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const {
    currentConversationId,
    messagesByConversation,
    pendingApprovals,
    approvalBusy,
    isStreaming,
    activeThinking,
    activeThinkingConversationId,
    error,
    setCurrentConversation,
    setConversations,
    upsertMessage,
    setWaiting,
    setActiveThinking,
    flushPendingMessage,
    setError,
    setApprovalBusy,
  } = useConversationStore((state) => state);
  const locale = useLocaleStore((state) => state.locale);

  const disclaimerText =
    locale === "zh" ? "内容由AI生成，重要信息请务必核查" : "Content generated by AI, please verify important information.";

  const visibleMessages = currentConversationId ? (messagesByConversation[currentConversationId] ?? []) : [];
  const lastMessageContent = visibleMessages[visibleMessages.length - 1]?.content ?? "";
  const visibleApprovals = currentConversationId
    ? pendingApprovals.filter((item) => item.conversationId === currentConversationId)
    : pendingApprovals;

  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  /** IME: ignore Enter for 200ms after compositionend to avoid sending on candidate confirm */
  const composingEndRef = useRef(false);

  useEffect(() => {
    const el = scrollContainerRef.current;
    if (!el || typeof el.scrollTo !== "function") return;
    const active = document.activeElement;
    const inputFocused =
      active && inputRef.current && (active === inputRef.current || inputRef.current.contains(active as Node));
    if (inputFocused && !isStreaming) return;
    requestAnimationFrame(() => {
      el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
    });
  }, [visibleMessages, visibleApprovals, activeThinking, error, isStreaming]);

  // Scroll when final text appears (e.g. after flush)
  useEffect(() => {
    const el = scrollContainerRef.current;
    if (!el || typeof el.scrollTo !== "function") return;
    const id = requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
      });
    });
    return () => cancelAnimationFrame(id);
  }, [lastMessageContent]);

  // Continuous scroll during thinking typewriter and streaming content
  useEffect(() => {
    const el = scrollContainerRef.current;
    if (!el || typeof el.scrollTo !== "function" || (!isStreaming && !activeThinking)) return;
    const id = setInterval(() => {
      const state = useConversationStore.getState();
      if (!state.isStreaming && !state.activeThinking) return;
      requestAnimationFrame(() => {
        el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
      });
    }, 150);
    return () => clearInterval(id);
  }, [isStreaming, activeThinking]);

  async function refreshConversations() {
    const conversations = await invoke<Conversation[]>("list_conversations");
    setConversations(conversations);
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const content = input.trim();
    if (!content) {
      return;
    }
    if (isStreaming || isSubmitting) {
      return;
    }
    setIsSubmitting(true);
    setError(null);
    setActiveThinking(null);
    const flushedConvId = flushPendingMessage();
    if (flushedConvId) void hydrateConversationMessages(flushedConvId);

    try {
      let conversationId = currentConversationId;
      if (!conversationId) {
        conversationId = await invoke<string>("create_conversation");
        setCurrentConversation(conversationId);
        await refreshConversations();
      }

      const userMessageId = `user-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
      const assistantMessageId = `assistant-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;

      upsertMessage({
        id: userMessageId,
        conversationId,
        role: "user",
        content,
      });

      upsertMessage({
        id: assistantMessageId,
        conversationId,
        role: "assistant",
        content: "",
      });

      setWaiting(true);

      await invoke<string>("send_message", {
        conversationId,
        content,
        assistantMessageId,
        userMessageId,
      });

      setInput("");
    } catch (caughtError: unknown) {
      const message = caughtError instanceof Error ? caughtError.message : String(caughtError);
      setError(`Error: ${message}`);
    } finally {
      setIsSubmitting(false);
    }
  }

  async function approvePending(approvalId: string) {
    setApprovalBusy(approvalId, true);
    try {
      await invoke("approve_action", { approvalId });
    } catch (caughtError: unknown) {
      const message = caughtError instanceof Error ? caughtError.message : String(caughtError);
      setError(`Error: ${message}`);
      setApprovalBusy(approvalId, false);
    }
  }

  async function rejectPending(approvalId: string) {
    setApprovalBusy(approvalId, true);
    try {
      await invoke("reject_action", { approvalId });
    } catch (caughtError: unknown) {
      const message = caughtError instanceof Error ? caughtError.message : String(caughtError);
      setError(`Error: ${message}`);
      setApprovalBusy(approvalId, false);
    }
  }

  return (
    <section className="chat-view">
      <div ref={scrollContainerRef} className="chat-view-scroll">
        <MessageList
          messages={visibleMessages}
          activeThinking={activeThinking}
          activeThinkingConversationId={activeThinkingConversationId}
          currentConversationId={currentConversationId}
          onThinkingComplete={() => {
            const convId = flushPendingMessage();
            if (convId) void hydrateConversationMessages(convId);
          }}
        />

        {error ? (
          <p role="alert" className="chat-error">
            {error}
          </p>
        ) : null}
      </div>

      {visibleApprovals.length > 0 ? (
        <div className="approval-list-wrapper">
          <section className="approval-list" aria-label="Pending approvals">
          {visibleApprovals.map((approval) => (
            <ApprovalCard
              key={approval.approvalId}
              approvalId={approval.approvalId}
              actionType={approval.actionType}
              path={approval.path}
              content={approval.content}
              busy={approvalBusy[approval.approvalId] === true}
              onApprove={approvePending}
              onReject={rejectPending}
            />
          ))}
          </section>
        </div>
      ) : null}

      <form className="chat-input-row" onSubmit={handleSubmit}>
        <div className="chat-input-wrapper">
          <textarea
            ref={inputRef}
            className="chat-input-field"
            value={input}
            onChange={(event) => setInput(event.currentTarget.value)}
            onCompositionStart={() => {
              composingEndRef.current = false;
            }}
            onCompositionEnd={() => {
              composingEndRef.current = true;
              setTimeout(() => {
                composingEndRef.current = false;
              }, 200);
            }}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                if (e.nativeEvent.isComposing || composingEndRef.current) {
                  return;
                }
                e.preventDefault();
                const form = e.currentTarget.form;
                if (form) form.requestSubmit();
              }
            }}
            placeholder="Send a message..."
            rows={3}
          />
          <div className="chat-input-bar">
            <div className="chat-input-left-icons" aria-hidden="true">
              <span className="chat-input-icon" title="Attach">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48" /></svg>
              </span>
              <span className="chat-input-icon" title="Mode">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" /><rect x="14" y="3" width="7" height="7" /><rect x="3" y="14" width="7" height="7" /><rect x="14" y="14" width="7" height="7" /></svg>
              </span>
              <span className="chat-input-icon" title="Pointer">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3l7.07 16.97 2.51-7.39 7.39-2.51L3 3z" /></svg>
              </span>
            </div>
            <button type="submit" className="chat-send-btn" disabled={isStreaming || isSubmitting} aria-label="Send">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="19" x2="12" y2="5" /><polyline points="5 12 12 5 19 12" /></svg>
            </button>
          </div>
        </div>
        <p className="chat-input-disclaimer">{disclaimerText}</p>
      </form>
    </section>
  );
}
